language: node_js
node_js:
  - "stable"
before_install: cd server
before_script:
  - npm install
script:
  - npm test
after_success: 
  - npm run coverage
  - npm run coveralls

env:
- CLOUDINARY_URL=cloudinary://924532231333791:RPagydm5nIN2CFgwcIPVkXWaiDU@dqxyecesu
- CODECLIMATE_REPO_TOKEN=d3708a9bcef91c58c706e9d2e0a4593501f6ab490dce979ed9b7d5a3afa79200
