
export default {
  cars: [
    {
      id: '123',
      owner: 1,
      created_on: new Date(),
      state: 'used',
      status: 'available',
      price: 2500000,
      manufacturer: 'toyota',
      model: 'camry',
      body_type: 'car',
      transmission_type: 'automatic',
      image_url: '',
      description: 'Fairly used toyota camry with auto transmission',
    },
    {
      id: '124',
      owner: 2,
      created_on: new Date(),
      state: 'New',
      status: 'available',
      price: 3000000,
      manufacturer: 'Mercedez',
      model: 'GLK',
      body_type: 'car',
      transmission_type: 'automatic',
      image_url: '',
      description: ' Brand new Benz GLK with latest functionalities',
    },
    {
      id: '125',
      owner: 3,
      created_on: new Date(),
      state: 'New',
      status: 'sold',
      price: 4500000,
      manufacturer: 'ford',
      model: 'ford express',
      body_type: 'SUV',
      transmission_type: 'automatic',
      image_url: '',
      description: ' Brand new ford express with latest functionalities',
    },
  ],
};

